baseURL = "http://www.devlog.host/"
languageCode = "pt-br"
title = "Devlog"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 3
enableRobotsTXT = true
disqusShortname = "devlog-unifil"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/css.css"]
  background_color_class = "bg-black"
  recent_posts_number = 2
  filename = "sitemap.xml"
  description = "Um blog de desenvolvimento."
  github = "https://github.com/Nakahwra/devlog"
  favicon = "https://img.icons8.com/cotton/2x/developer.png"